apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer  # Change to ClusterIP if you want to access it internally

